project:
  type: book

book:
  title: "Prometheus: Unofficial User Guide"
  subtitle: ""
  author: "Sam LaCarte"
  date: "2026-03-14"
  chapters:
    - index.qmd
    - summary.qmd
    - intro.qmd
    - installation.qmd
    - data-gathering-formatting.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

