project:
  type: book

book:
  title: "prometheus-user-guide"
  author: "Sam LaCarte"
  date: "2026-03-14"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

